### ISSUE TITLE
Reading theme state?

### ISSUE THREAD

**Issue by samuli-as** [Artanicus/python-cozify#20]
Hi,

is it possible to get active themes via python-cozify in any way? Themes were briefly mentioned in the related thread on the Cozify forum. I understood that the hub does expose them but that's not supported by this project yet. Is this correct?

**Comment by samuli-as** [comment]
Awesome, thanks! It's been a while since I have touched python but I'll give it a shot.

**Comment by samuli-as** [comment]
I got the basic stuff working. Changing scene states works too. I tried to keep things consistent with existing code. There are no tests yet. Fiddling with what is basically the production environment is scary enough as it is. ;) https://github.com/Artanicus/python-cozify/pull/21

**Comment by Artanicus** [comment]
Code is merged and I added some basic tests to check sanity and test toggling if there's a scene called `test`. Overall the test suite doesn't still pass 100% because of silly lights that are tricksy with color changes but all other tests pass!

Will make a new release now.
